//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLayer2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marker
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public string Image { get; set; }
        public string Intro { get; set; }
    }
}
